# Generated by Django 4.1.4 on 2023-02-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
